### ISSUE TITLE
installing kubernetes sysext on azure doesn't autostart kubelet

### ISSUE THREAD

**Issue by jepio** [flatcar/sysext-bakery#50]
## Description

Kubelet is not autostarted after a reboot. In the merged /usr `ls /usr/lib/systemd/multi-user.target.d` shows that only the waagent conf is present. Manually mounting the kubernetes sysext confirms that it has a config that should uphold it.

## Impact

[ 1 sentence detailing the impact this bug is creating for you ]

## Environment and steps to reproduce

1. **Set-up**: [ describe the environment Flatcar/Lokomotive/Nebraska etc was running in when encountering the bug; Platform etc. ]
2. **Task**: [ describe the task performing when encountering the bug ]
3. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. [ requested the start of a new pod or container ]
  b. [ container image downloaded ]
4. **Error**: [describe the error that was triggered]

## Expected behavior

[ describe what you expected to happen at 4. above but instead got an error ]

## Additional information

Please add any information here that does not fit the above format.

**Comment by pothos** [comment]
Turns out it was also masking the containerd upholds we ship through the internal containerd sysext
