### ISSUE TITLE
Fix bake_flatcar_image.sh to allow adding several sysext overlays at once

### ISSUE THREAD

**Issue by jsalatiel** [flatcar/sysext-bakery#55]
## Description
According to the script help, I should be able to run:
```
bake_flatcar_image.sh --release beta --vendor qemu_uefi sysext1:sysext1.raw sysext2:sysext2.raw  sysext3:sysext3.raw  ...
```
The problem is that only the first sysext package will be added to the final image. The remaining are just ignored.

## Impact
Cant add several sysext overlays at once

## Environment and steps to reproduce
1. Create some sysext
2. Try to add more then one using the current syntax

## Expected behavior
It should add all images

**Comment by t-lo** [comment]
Thank you for reporting this! Unfortunately I'm unable to repro... We merged a bugfix yesterday which might have improved the situation: https://github.com/flatcar/sysext-bakery/pull/56

I just ran
```
./bake_flatcar_image.sh --release alpha --vendor qemu_uefi wasmtime:wasmtime-18.0.1-x86-64.raw kubernetes:kubernetes-v1.29.2-x86-64.raw
```
with wasmtime and kubernetes downloaded from the bakery and ended up with a qemu image that had both included.

If it's still broken for you, could you please run
```bash
bake_flatcar_image.sh --release beta --vendor qemu_uefi sysext1:sysext1.raw sysext2:sysext2.raw  sysext3:sysext3.raw  2>&1 | tee log
```
and then attach `log` to this issue?

**Comment by jsalatiel** [comment]
#56 fixed the problem for me.
Thanks!
