### ISSUE TITLE
[RFE] New release to include wasmcloud

### ISSUE THREAD

**Issue by t-lo** [flatcar/sysext-bakery#58]
## Current situation

Recently, support for building wasmcloud sysexts was added: https://github.com/flatcar/sysext-bakery/pull/54
But the latest release is from February.

## Impact

A pre-built wasmcloud sysext is not available from the bakery release page.

## Ideal future situation

A pre-built wasmcloud sysext is available from the bakery release page.

## Implementation options

Run the release github action.

## Additional information

(this issue is filed mainly for release coordination since we do not have a formal bakery release process yet)

**Comment by joonas** [comment]
Not that I imagine this needs any further motivation, but it's worth mentioning that the changes merged in #54 included an inclusion of a new example to the README that references artifacts which are currently not available in the latest release (namely, the wasmcloud conf and image)

**Comment by pothos** [comment]
I added the tag now, I had thought that the other PRs get ready at the same time but it seems to take a bit more.
